---
# tasks file for tomcat
- name: install tomcat
  yum:
    name: tomcat
    state: latest
- name: enable tomcat at boot 
  service:
    name: tomcat
    enabled: yes
- name: create temp
  file:
    path: /usr/share/tomcat/webapps/ROOT
    state: directory
- name: make Entry in index
  template:
    src: index.html.j2
    dest: /usr/share/tomcat/webapps/ROOT/index.html
    mode: 0644
- name: start tomcat
  service:
    name: tomcat
    state: started



